### ISSUE TITLE
Tauri panic in dev mode. Missing icon.

### ISSUE THREAD

**Issue by gnprwx** [nhexirc/client#4]
When attempting to run nhex with the command `npm run tauri dev`, I receive the following error.

```sh
error: proc macro panicked
  --> src/main.rs:86:14
   |
86 |         .run(tauri::generate_context!())
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: failed to read icon /Users/null/Documents/dev/nhex/src-tauri/icons/icon.png: No such file or directory (os error 2)

error: could not compile `nhex` (bin "nhex") due to 1 previous error
```

This happens on a macbook pro m1, and the only image I can find in src-tauri is `nhex.png`, so the error is indeed correct.

**Comment by terrablue** [comment]
Can confirm the same error on a Linux system (Arch, Thinkpad x1).

**Comment by edfletcher** [comment]
@gnprwx pushed https://github.com/nhexirc/client/commit/b07ac62cd82f9f45e0865ac76a0996dc93ae19e6 with the fix @terrablue mentioned in-channel: let me know if it can build & run on your system with this, and feel free to close this out if so. Thank you again! 🚀

**Comment by gnprwx** [comment]
Works!
